### ISSUE TITLE
does not support the provided sort type undefined

### ISSUE THREAD

**Issue by axano** [mmckeaveney/clinews#5]
I get the following error when entering "```news fetch fox-news``` ":

```The selected news source fox-news does not support the provided sort type (undefined). Please try another sort type. The 3 sort types are popular, top and latest.```

I get the same error when issuing :

```news fetch fox-news -s top```

**Comment by shogunpurple** [comment]
Just seeing this. Thanks for the report - I'm able to reproduce. Will let you know when I've published a fix 👍

**Comment by shogunpurple** [comment]
@axano fixed in 1.1.0. Thanks again!
